--!strict
-- Generated by Luna from one captured reflection generation.
-- Module: studio.physics@2.1.0
-- Module: studio.units@1.0.0

-- One declared shape.
declare class Studio_Shape
  read Corners: number
end

-- One documented gadget.
declare class Studio_Gadget extends Studio_Shape
  -- Adds to the charge.
  function Boost(self: Studio_Gadget, Argument1: number): number
  Charge: number
  -- Twice the stored charge.
  read Level: number
  function __len(self: Studio_Gadget): number
end

declare function Describe(Argument1: string): string

-- Physics helpers.
declare Physics: {
  Blend: ((number, number) -> number) & ((string) -> string), -- studio.physics@2.1.0
  Enabled: boolean, -- studio.physics@2.1.0
  Epsilon: number, -- studio.physics@2.1.0
  -- Metres per second squared.
  Gravity: number, -- studio.physics@2.1.0
  Offset: (number, number?) -> number, -- studio.physics@2.1.0
  Reset: () -> (), -- studio.physics@2.1.0
  -- Doubles one value.
  Scale: (number) -> number, -- studio.physics@2.1.0
  -- The iterative solver.
  Solver: {
    Iterations: number, -- studio.physics@2.1.0
    Solve: (number) -> number, -- studio.physics@2.1.0
  }, -- studio.physics@2.1.0
  Split: (string) -> (number, string), -- studio.physics@2.1.0
  Total: (...any) -> number, -- studio.physics@2.1.0
  Trim: (number, number?) -> number, -- studio.physics@2.1.0
} -- studio.physics@2.1.0

declare Studio: {
  -- One documented gadget.
  Gadget: {
    Describe: () -> string,
    FromCharge: (number) -> Studio_Gadget,
    New: () -> Studio_Gadget,
  },
  -- The palette.
  Palette: {
    Blue: number,
    Green: number,
    Primary: number,
    -- The red enumerator.
    Red: number,
  },
  -- One declared shape.
  Shape: {
    New: () -> Studio_Shape,
  },
}

-- Base units.
declare Units: {
  -- One metre.
  Metre: number, -- studio.units@1.0.0
  Name: string, -- studio.units@1.0.0
} -- studio.units@1.0.0

declare Version: string

