#pragma once

// Deterministic Luau `.d.lua` declaration generation. Generation reads one
// explicitly captured immutable `ReflectionSnapshot` and one immutable options
// value, and nothing else: no State, no virtual machine, no table, no dispatch
// target, and no native object is consulted, so a snapshot retained across
// later registrations, a freeze, a State move, or destruction of the
// originating State still declares exactly the surface it captured.
//
// The traversal is the same canonical order documentation generation uses -
// module provenance, then scope qualified name, symbol kind, declaration
// signature, and stable identity - so equivalent snapshot content and equal
// options always produce byte-identical UTF-8 output without a byte-order mark
// and with LF line endings, independent of registration order, addresses,
// locale, hash iteration, and process-random values.
//
// Only metadata that maps onto a representable Luau declaration is emitted.
// Metadata that Luau cannot declare, names a type Luau has no representation
// for, or contradicts itself produces one deterministic rejection carrying no
// bytes at all, rather than a guessed or incorrect declaration.

// clang-format off
#include <luna/generation/artifact.hpp>
#include <luna/reflection/reflection_snapshot.hpp>

#include <string>
#include <string_view>
#include <utility>
// clang-format on

namespace Luna {

// Immutable declaration generator options. Every option is a value: an options
// object is never rebound after generation begins, and two equal options always
// select the same output.
class DeclarationOptions final {
public:
  // The canonical banner used when a caller states none.
  static constexpr std::string_view DefaultBanner =
      "Generated by Luna from one captured reflection generation.";

  DeclarationOptions() = default;

  [[nodiscard]] static DeclarationOptions Create(std::string Banner,
                                                 bool IncludeStrictMode,
                                                 bool IncludeProvenance,
                                                 bool IncludeDocumentation) {
    DeclarationOptions Options;
    Options.BannerValue = std::move(Banner);
    Options.StrictModeValue = IncludeStrictMode;
    Options.ProvenanceValue = IncludeProvenance;
    Options.DocumentationValue = IncludeDocumentation;
    return Options;
  }

  // The leading banner comment. An empty banner selects `DefaultBanner`, so a
  // generated file is never unattributed.
  [[nodiscard]] std::string_view Banner() const noexcept {
    return BannerValue.empty() ? DefaultBanner : std::string_view(BannerValue);
  }

  // Emit the `--!strict` mode line ahead of every declaration.
  [[nodiscard]] bool IncludesStrictMode() const noexcept {
    return StrictModeValue;
  }

  // Name the module and version each declaration came from.
  [[nodiscard]] bool IncludesProvenance() const noexcept {
    return ProvenanceValue;
  }

  // Carry declared documentation text into Luau comments.
  [[nodiscard]] bool IncludesDocumentation() const noexcept {
    return DocumentationValue;
  }

  [[nodiscard]] DeclarationOptions WithBanner(std::string Banner) const {
    DeclarationOptions Options = *this;
    Options.BannerValue = std::move(Banner);
    return Options;
  }

  [[nodiscard]] DeclarationOptions WithStrictMode(bool Include) const {
    DeclarationOptions Options = *this;
    Options.StrictModeValue = Include;
    return Options;
  }

  [[nodiscard]] DeclarationOptions WithProvenance(bool Include) const {
    DeclarationOptions Options = *this;
    Options.ProvenanceValue = Include;
    return Options;
  }

  [[nodiscard]] DeclarationOptions WithDocumentation(bool Include) const {
    DeclarationOptions Options = *this;
    Options.DocumentationValue = Include;
    return Options;
  }

  [[nodiscard]] friend bool operator==(const DeclarationOptions &Left,
                                       const DeclarationOptions &Right) {
    return Left.Banner() == Right.Banner() &&
           Left.StrictModeValue == Right.StrictModeValue &&
           Left.ProvenanceValue == Right.ProvenanceValue &&
           Left.DocumentationValue == Right.DocumentationValue;
  }

private:
  std::string BannerValue;
  bool StrictModeValue = true;
  bool ProvenanceValue = true;
  bool DocumentationValue = true;
};

// Generates the complete Luau `.d.lua` declarations of one captured reflection
// generation. The whole artifact is built and validated in an owned buffer
// first: an accepted artifact is canonical UTF-8 with LF line endings, and a
// rejected artifact carries one deterministic diagnostic and no bytes.
[[nodiscard]] GeneratedArtifact
GenerateDeclarations(const ReflectionSnapshot &Snapshot,
                     const DeclarationOptions &Options);

} // namespace Luna
