#pragma once

// clang-format off
#include <luna/generation/artifact.hpp>
#include <luna/reflection/reflection_snapshot.hpp>

#include <string>
#include <string_view>
#include <utility>
// clang-format on

namespace Luna {

class DeclarationOptions final {
public:
  static constexpr std::string_view DefaultBanner =
      "Generated by Luna from one captured reflection generation.";

  DeclarationOptions() = default;

  [[nodiscard]] static DeclarationOptions Create(std::string Banner,
                                                 bool IncludeStrictMode,
                                                 bool IncludeProvenance,
                                                 bool IncludeDocumentation) {
    DeclarationOptions Options;
    Options.BannerValue = std::move(Banner);
    Options.StrictModeValue = IncludeStrictMode;
    Options.ProvenanceValue = IncludeProvenance;
    Options.DocumentationValue = IncludeDocumentation;
    return Options;
  }

  [[nodiscard]] std::string_view Banner() const noexcept {
    return BannerValue.empty() ? DefaultBanner : std::string_view(BannerValue);
  }

  [[nodiscard]] bool IncludesStrictMode() const noexcept {
    return StrictModeValue;
  }

  [[nodiscard]] bool IncludesProvenance() const noexcept {
    return ProvenanceValue;
  }

  [[nodiscard]] bool IncludesDocumentation() const noexcept {
    return DocumentationValue;
  }

  [[nodiscard]] DeclarationOptions WithBanner(std::string Banner) const {
    DeclarationOptions Options = *this;
    Options.BannerValue = std::move(Banner);
    return Options;
  }

  [[nodiscard]] DeclarationOptions WithStrictMode(bool Include) const {
    DeclarationOptions Options = *this;
    Options.StrictModeValue = Include;
    return Options;
  }

  [[nodiscard]] DeclarationOptions WithProvenance(bool Include) const {
    DeclarationOptions Options = *this;
    Options.ProvenanceValue = Include;
    return Options;
  }

  [[nodiscard]] DeclarationOptions WithDocumentation(bool Include) const {
    DeclarationOptions Options = *this;
    Options.DocumentationValue = Include;
    return Options;
  }

  [[nodiscard]] friend bool operator==(const DeclarationOptions &Left,
                                       const DeclarationOptions &Right) {
    return Left.Banner() == Right.Banner() &&
           Left.StrictModeValue == Right.StrictModeValue &&
           Left.ProvenanceValue == Right.ProvenanceValue &&
           Left.DocumentationValue == Right.DocumentationValue;
  }

private:
  std::string BannerValue;
  bool StrictModeValue = true;
  bool ProvenanceValue = true;
  bool DocumentationValue = true;
};

[[nodiscard]] GeneratedArtifact
GenerateDeclarations(const ReflectionSnapshot &Snapshot,
                     const DeclarationOptions &Options);

} // namespace Luna
